# Generated by Django 5.1.6 on 2025-04-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Rented'), ('1', 'Returned'), ('2', 'Lost'), ('3', 'Delayed')], default='0', max_length=2)),
                ('rent_start_date', models.DateField(help_text='Rental start date')),
                ('rent_end_date', models.DateField(blank=True, help_text='Rental deadline')),
                ('return_date', models.DateField(blank=True, help_text='Return date', null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
