# Generated by Django 5.1.6 on 2025-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='is_closer',
            new_name='is_closed',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_end_date',
            field=models.DateField(blank=True, help_text='Rental deadline'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_start_date',
            field=models.DateField(help_text='Rental start date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(blank=True, help_text='Return date', null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('0', 'Rented'), ('1', 'Returned'), ('2', 'Lost'), ('3', 'Delayed')], default='0', max_length=2),
        ),
    ]
